### ISSUE TITLE
IntegerField for user_id

### ISSUE THREAD

**Issue by coder2020official** [mirsaid-mirzohidov/blog-bot#1]
⚠️ WARNING! ⚠️
After one of the upcoming Bot API updates, user identifiers will become bigger than 2^31 - 1 and it will be no longer possible to store them in a signed 32-bit integer type. User identifiers will have up to 52 significant bits, so a 64-bit integer or double-precision float type would still be safe for storing them. Please make sure that your code can correctly handle such user identifiers.

This warning should not be ignored, so edit your models.py, use Bigintegerfield for storing user id.

**Comment by themir8** [comment]
Thanks!
